### ISSUE TITLE
这个能用vue做吗？怎么全是兼容报错

### ISSUE THREAD

**Issue by jinbiaode** [KID-1912/tiptap-appmsg-editor#1]
请问下 能转用vue框架吗？怎么我用vue一堆兼容性报错，作者可否给个vue的？非常感谢！~

**Comment by KID-1912** [comment]
已使用 vite+vue3 改写，可见 [vue-tiptap-appmsg-editor](https://github.com/KID-1912/vue-tiptap-appmsg-editor)
